"""
Django settings for meu_site project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads secrets (like ANTHROPIC_API_KEY) from a local ".env" file at the repo
# root — that file is gitignored and never committed.
load_dotenv(BASE_DIR.parent / '.env')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production (Render), SECRET_KEY is set as an environment variable —
# this hardcoded value is only ever used for local development.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-t-(99-9dz^q20&-zeye$!0ii2kvv&07hmt_2b)p)&$87tm&u%f',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS', 'testserver,127.0.0.1,localhost'
).split(',')

# Needed for POST requests (e.g. login) to work behind Render's HTTPS proxy —
# without it Django's CSRF check rejects the request's Origin as untrusted.
CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'meu_site.apps.MeuSiteConfig',
]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meu_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meu_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# In production, DATABASE_URL (set in the Render dashboard, not committed —
# see render.yaml) points at a Neon Postgres instance, which survives
# deploys/restarts — Render's own disk doesn't (it's wiped on every deploy
# and when a free-plan instance spins down), which was silently resetting
# student data there. Locally, with no DATABASE_URL set, this falls back to
# SQLite at SQLITE_DB_PATH (see .env) — a folder OUTSIDE any cloud-sync
# client, for the same reason (see git history for the OneDrive incident).
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{os.environ.get('SQLITE_DB_PATH') or (BASE_DIR / 'db.sqlite3')}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Static files
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR.parent / 'static',
]

# Where `collectstatic` gathers everything for production — whitenoise then
# serves it directly from the app process, no separate static host needed.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
