# Generated by Django 6.1 on 2026-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0002_perfilaluno_progress_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao', models.CharField(choices=[('fotossintese', 'Fotossíntese'), ('mitose', 'Mitose'), ('meiose', 'Meiose')], default='fotossintese', max_length=50)),
                ('enunciado', models.TextField(verbose_name='Pergunta')),
                ('opcao_a', models.CharField(max_length=250, verbose_name='Opção A')),
                ('opcao_b', models.CharField(max_length=250, verbose_name='Opção B')),
                ('opcao_c', models.CharField(max_length=250, verbose_name='Opção C')),
                ('opcao_d', models.CharField(max_length=250, verbose_name='Opção D')),
                ('resposta_correta', models.CharField(choices=[('A', 'Opção A'), ('B', 'Opção B'), ('C', 'Opção C'), ('D', 'Opção D')], max_length=1, verbose_name='Resposta Correta')),
                ('xp_recompensa', models.IntegerField(default=50, verbose_name='XP de Recompensa')),
            ],
            options={
                'verbose_name': 'Pergunta de Quiz',
                'verbose_name_plural': 'Perguntas de Quiz',
            },
        ),
    ]
