# Generated by Django 6.1 on 2026-09-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0003_perguntaquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilaluno',
            name='titulo_atual',
            field=models.CharField(default='Aprendiz', max_length=100),
        ),
    ]
