# Generated by Django 6.1 on 2026-09-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0004_alter_perfilaluno_titulo_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='progresso_secoes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
