# Generated by Django 6.1 on 2026-09-03 22:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0005_perfilaluno_progresso_secoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='plano',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=4),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='uso_chat_semana',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='InqueritoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_escolar', models.CharField(blank=True, choices=[('10', '10º ano'), ('11', '11º ano'), ('12', '12º ano')], max_length=2)),
                ('curso_pretendido', models.CharField(blank=True, max_length=200)),
                ('niveis_disciplinas', models.JSONField(blank=True, default=dict)),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
