# Generated by Django 6.1 on 2026-09-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0006_perfilaluno_plano_perfilaluno_uso_chat_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='progresso_testes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
