# Generated by Django 6.1 on 2026-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0007_perfilaluno_progresso_testes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='perguntas_erradas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
