# Generated by Django 6.1 on 2026-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0008_perfilaluno_perguntas_erradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
