# Generated by Django 6.1 on 2026-09-21 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0009_perfilaluno_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='sequencia_recorde',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='vocabulario_estado',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ResultadoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('teste', 'Teste'), ('exame', 'Exame'), ('missao_seccao', 'Secção de missão')], max_length=20)),
                ('identificador', models.CharField(max_length=150)),
                ('unidade', models.CharField(blank=True, default='', max_length=30)),
                ('nota_percentagem', models.FloatField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_avaliacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistoAtividadeDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('minutos', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_atividade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('user', 'data')},
            },
        ),
    ]
